CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
  --stage sft \
  --do_train \
  --model_name_or_path meta-llama/Llama-3.2-3B \
  --dataset gsm8k \
  --dataset_dir /upb/users/s/sashreek/profiles/unix/cs/HTYLLM-PG/approaches/CoLA/LLaMA-Factory/data \
  --template llama3 \
  --finetuning_type hydralora \
  --output_dir ./saves/smoke_test \
  --overwrite_output_dir \
  --num_train_epochs 1 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --lora_rank 4 \
  --lora_alpha 8 \
  --lora_num 3 \
  --use_hydralora_experts \
  --hydralora_num_experts 4 \
  --hydralora_top_k 2